### ISSUE TITLE
Relation to Spark.jl

### ISSUE THREAD

**Issue by dfdx** [propelledanalytics/SparkSQL.jl#4]
Going through the code of SparkSQL.jl I find a lot of features similar to those in [Spark.jl](https://github.com/dfdx/Spark.jl), including JVM initialization, Spark session management, SQL operations, etc. I wonder if you have seen that package and, if so, what do you think about relation between the two? Are there significant differences? Do these packages should co-exist or one should supersede another?

**Comment by propelledanalytics** [comment]
SparkSQL.jl is only focused on providing an SQL interface for Julia tabular data in the cloud and on premise.   Its target usage is Data Lakehouses including Delta lake and Apache Iceberg (along with Parquet, JSON, CSV).   The package has support for more SQL datatypes like Date, TimeStamp, and Decimal.  Because the focus is purely on Spark SQL the package will not have an RDD interface.  

SparkSQL.jl uses the JavaCall.jl Julia package to access the JVM.

Spark.jl seems focused on Spark resilient distributed datasets (RDD).  Therefore, these packages should co-exist because the use cases are different.

**Comment by dfdx** [comment]
> Spark.jl seems focused on Spark resilient distributed datasets (RDD).

Actually, not. Spark.jl was created at the time of Spark 1.x series which had _only_ RDD API. But as the community moved mostly to Dataset API, so did Spark.jl. We even have an [issue for abandoning RDD API](https://github.com/dfdx/Spark.jl/issues/86) altogether (blocked by UDF stuff though). 

Given that the 2 projects have very similar purposes and similar code base, I thought joining the effort might be a good idea. But anyway, if you need any promotion from the Spark.jl side, please let me know.
