### ISSUE TITLE
Julia UDFs

### ISSUE THREAD

**Issue by dfdx** [propelledanalytics/SparkSQL.jl#5]
One of the core features of Spark SQL (Scala & Python API) is the ability to run custom UDFs in SQL queries. However, extending UDF support to other languages turned to be [quite a hard task](https://github.com/dfdx/Spark.jl/issues/86#issuecomment-782441438). 

Have you considered Julia UDFs in SparkSQL.jl?

**Comment by propelledanalytics** [comment]
SparkSQL is focused on providing Julia programmers tabular data access to Spark using only SQL.  UDFs in Julia are out of scope because SparkSQL.jl needs to access data on architectures and operating systems that do not support Julia including z/OS (mainframe).  The supported SparkSQL.jl way to run custom Julia logic is to query data, bring it to Julia as a DataFrame, transform it, and push the result to a DataSet on Spark.
